// Utility functions for exporting valuation data

import { ValuationOutput, ValuationInput } from './types';

export function generateBrokerSummary(
  valuation: ValuationOutput,
  input: ValuationInput
): string {
  const { valuationRange, industryData, normalizedFinancials, multiplesUsed, totalRiskAdjustment } = valuation;

  const formatCurrency = (value: number): string => {
    if (value >= 1000000) {
      return `$${(value / 1000000).toFixed(2)}M`;
    } else if (value >= 1000) {
      return `$${(value / 1000).toFixed(0)}K`;
    }
    return `$${value.toLocaleString()}`;
  };

  let summary = `BUSINESS VALUATION SUMMARY\n`;
  summary += `==========================================\n\n`;

  if (input.businessName) {
    summary += `Business: ${input.businessName}\n`;
  }
  summary += `Industry: ${industryData.industryName}\n`;
  if (industryData.naicsCode && industryData.naicsCode !== 'default') {
    summary += `NAICS Code: ${industryData.naicsCode}\n`;
  }
  summary += `\n`;

  summary += `VALUATION RANGE\n`;
  summary += `Low:  ${formatCurrency(valuationRange.low)}\n`;
  summary += `Mid:  ${formatCurrency(valuationRange.mid)}\n`;
  summary += `High: ${formatCurrency(valuationRange.high)}\n`;
  summary += `\n`;

  summary += `FINANCIAL INPUTS\n`;
  if (input.revenue) summary += `Annual Revenue: ${formatCurrency(input.revenue)}\n`;
  summary += `SDE: ${formatCurrency(normalizedFinancials.sde)}\n`;
  summary += `EBITDA: ${formatCurrency(normalizedFinancials.ebitda)}\n`;
  if (input.askingPrice) {
    summary += `Asking Price: ${formatCurrency(input.askingPrice)}\n`;
  }
  summary += `\n`;

  summary += `METHODOLOGY\n`;
  summary += `Primary Method: ${multiplesUsed.primaryMethod.toUpperCase()}\n`;
  summary += `Base Multiple Range: ${multiplesUsed[multiplesUsed.primaryMethod].low.toFixed(2)}x - ${multiplesUsed[multiplesUsed.primaryMethod].high.toFixed(2)}x\n`;
  summary += `Risk Adjustment: ${totalRiskAdjustment > 0 ? '+' : ''}${totalRiskAdjustment.toFixed(2)}x\n`;
  summary += `\n`;

  if (valuation.keyStrengths.length > 0) {
    summary += `KEY STRENGTHS\n`;
    valuation.keyStrengths.forEach((strength, i) => {
      summary += `${i + 1}. ${strength}\n`;
    });
    summary += `\n`;
  }

  if (valuation.redFlags.length > 0) {
    summary += `RISK FACTORS\n`;
    valuation.redFlags.forEach((flag, i) => {
      summary += `${i + 1}. ${flag}\n`;
    });
    summary += `\n`;
  }

  if (valuation.mispricing) {
    summary += `ASKING PRICE ANALYSIS\n`;
    summary += `${valuation.mispricing.label}\n`;
    summary += `${valuation.mispricing.analysis}\n`;
    summary += `\n`;
  }

  summary += `==========================================\n`;
  summary += `Generated by Succedence Valuation Tool\n`;
  summary += `Note: This is an estimate, not a certified appraisal.\n`;

  return summary;
}

export function generateSellerRationale(
  valuation: ValuationOutput,
  input: ValuationInput
): string {
  const { valuationRange, industryData, dealQualityScore } = valuation;

  const formatCurrency = (value: number): string => {
    if (value >= 1000000) {
      return `$${(value / 1000000).toFixed(1)}M`;
    } else if (value >= 1000) {
      return `$${(value / 1000).toFixed(0)}K`;
    }
    return `$${value.toLocaleString()}`;
  };

  let rationale = ``;

  if (input.businessName) {
    rationale += `Regarding the valuation of ${input.businessName}:\n\n`;
  } else {
    rationale += `Regarding the business valuation:\n\n`;
  }

  rationale += `Based on our analysis of ${industryData.industryName} businesses and current market data, the estimated value range is ${formatCurrency(valuationRange.low)} to ${formatCurrency(valuationRange.high)}, with a midpoint of ${formatCurrency(valuationRange.mid)}.\n\n`;

  rationale += `This valuation is derived from recent transaction data for similar businesses in your industry, adjusted for the specific characteristics of your operation. `;

  if (valuation.keyStrengths.length > 0) {
    rationale += `Key value drivers include ${valuation.keyStrengths.slice(0, 2).join(' and ').toLowerCase()}. `;
  }

  if (valuation.redFlags.length > 0 && dealQualityScore < 70) {
    rationale += `We've also considered areas that may impact value, such as ${valuation.redFlags[0].toLowerCase()}. `;
  }

  if (input.askingPrice && valuation.mispricing) {
    const variance = ((input.askingPrice - valuationRange.mid) / valuationRange.mid * 100).toFixed(0);
    if (Math.abs(parseFloat(variance)) > 15) {
      if (parseFloat(variance) > 0) {
        rationale += `\n\nThe current asking price of ${formatCurrency(input.askingPrice)} is ${Math.abs(parseFloat(variance))}% above our valuation midpoint. `;
        rationale += `While your business has unique strengths, I'd recommend we discuss positioning to ensure strong buyer interest.`;
      } else {
        rationale += `\n\nThe current asking price of ${formatCurrency(input.askingPrice)} appears competitive based on market comparables.`;
      }
    }
  }

  rationale += `\n\nI'm happy to discuss the methodology and answer any questions you may have about how we arrived at this range.`;

  return rationale;
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy to clipboard:', err);
    return false;
  }
}
